// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf-ifIEgNMr_l39PvhNyGvIXQm39xDJUg',
    appId: '1:469236570222:web:abf1507242e7460330ee7f',
    messagingSenderId: '469236570222',
    projectId: 'ranksprintai-1eff8',
    authDomain: 'ranksprintai-1eff8.firebaseapp.com',
    storageBucket: 'ranksprintai-1eff8.firebasestorage.app',
    measurementId: 'G-KDTNQFY9B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAkfRiSqFQVqhPXXbpZ7ywjBP5vmaoq94',
    appId: '1:469236570222:android:ae32b29256347c3c30ee7f',
    messagingSenderId: '469236570222',
    projectId: 'ranksprintai-1eff8',
    storageBucket: 'ranksprintai-1eff8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvMUSQWWlWAnsYze_AWjl5AmQaZrXOleE',
    appId: '1:469236570222:ios:e98e5d8866e6225430ee7f',
    messagingSenderId: '469236570222',
    projectId: 'ranksprintai-1eff8',
    storageBucket: 'ranksprintai-1eff8.firebasestorage.app',
    iosBundleId: 'com.example.ranksprint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvMUSQWWlWAnsYze_AWjl5AmQaZrXOleE',
    appId: '1:469236570222:ios:e98e5d8866e6225430ee7f',
    messagingSenderId: '469236570222',
    projectId: 'ranksprintai-1eff8',
    storageBucket: 'ranksprintai-1eff8.firebasestorage.app',
    iosBundleId: 'com.example.ranksprint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf-ifIEgNMr_l39PvhNyGvIXQm39xDJUg',
    appId: '1:469236570222:web:82535637f60778ae30ee7f',
    messagingSenderId: '469236570222',
    projectId: 'ranksprintai-1eff8',
    authDomain: 'ranksprintai-1eff8.firebaseapp.com',
    storageBucket: 'ranksprintai-1eff8.firebasestorage.app',
    measurementId: 'G-HN3DR28XHT',
  );

}