// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdRlA_h0OBrgn3QLNDFXlEpQPIRkQJJlw',
    appId: '1:860899860233:web:07e0f64ce91b70c1633dd8',
    messagingSenderId: '860899860233',
    projectId: 'ranksprint',
    authDomain: 'ranksprint.firebaseapp.com',
    storageBucket: 'ranksprint.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDWde0ByUjtKkhZKpWMaWemvUcfXWWD64',
    appId: '1:860899860233:android:b9b9f1c4b77504be633dd8',
    messagingSenderId: '860899860233',
    projectId: 'ranksprint',
    storageBucket: 'ranksprint.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqCgFwRy3PRpZ0dZNl-bCYvwqU3samvXM',
    appId: '1:860899860233:ios:97aecbfc3b361ddf633dd8',
    messagingSenderId: '860899860233',
    projectId: 'ranksprint',
    storageBucket: 'ranksprint.firebasestorage.app',
    iosBundleId: 'com.example.ranksprint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqCgFwRy3PRpZ0dZNl-bCYvwqU3samvXM',
    appId: '1:860899860233:ios:97aecbfc3b361ddf633dd8',
    messagingSenderId: '860899860233',
    projectId: 'ranksprint',
    storageBucket: 'ranksprint.firebasestorage.app',
    iosBundleId: 'com.example.ranksprint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdRlA_h0OBrgn3QLNDFXlEpQPIRkQJJlw',
    appId: '1:860899860233:web:3f094ccbce4df82c633dd8',
    messagingSenderId: '860899860233',
    projectId: 'ranksprint',
    authDomain: 'ranksprint.firebaseapp.com',
    storageBucket: 'ranksprint.firebasestorage.app',
  );
}
